apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
  namespace: rbac
spec:
  selector:
    matchLabels:
      app: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: dev
    spec:
      serviceAccountName: rbac-dev
      containers:
      - name: dev
        image: dtzar/helm-kubectl
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]